#!/usr/bin/env python

import fileinput
import sys
from base64 import b64encode, b64decode

args = sys.argv[1:]
if len(args) <= 0:
    pass

indata = ''.join([line for line in fileinput.input()])
outdata = b64decode(indata.replace('\n', ''))
sys.stdout.write(outdata)
sys.stdout.flush()


