#!/usr/bin/env python3

import fileinput
import sys
from base64 import b64encode, b64decode

indata = b''.join([line for line in fileinput.input(mode='rb')])
outdata = b64encode(indata)


sys.stdout.buffer.write(outdata)
sys.stdout.buffer.flush()
