#!/bin/bash

#dir="`dirname \"$0\"`"
#@"$dir/bc-script-compare-two-files.txt" 

#cat <<EOF
#beyond-compare "$@" -fv="Text Compare"
#EOF
#"$(beyond-compare)" "$@" -fv="Text Compare"
bcomp "$@" -fv="Text Compare"


