#!/bin/bash

ccode "$@" | resub --multiline '^class [^;]*? { [\s]* .*? ^ [\s]* }; [\s]*' --find | resub --multiline '}; [\s]*? ^ class' '}\n\n//==============================================================================\n\nclass'

