#!/bin/sh

port="${1}"
shift 1
url="${1}"
shift 1

if [ -z "${port}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <port> <url> [<option>]"
    exit 1
fi

if [ -z "${url}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <port> <url> [<option>]"
    exit 1
fi

file="$(basename "${url}")"

exec curl --socks5 "localhost:${port}" -fsSL "$url" -o "$file" "$@"

