#!/bin/bash

port="${1}"
shift 1
url="${1}"
shift 1

if [ -z "${port}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <port> <url> [<option>]"
    exit 1
fi

if [ -z "${url}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <port> <url> [<option>]"
    exit 1
fi

file="$(basename "${url}")"

if [ ! -f "$file" ]
then
  set -x

  curl --socks5 "localhost:${port}" -fsSL "$url" -o "${file}.tmp" "$@" || rm -f "${file}.tmp"
  mv "${file}.tmp" "${file}" 2>/dev/null
else
  echo "Skipping existing file: $file" 1>&2
fi

