#!/bin/bash

# standard dotfiles. Currently (01-04-2023) evaluates to:
# /etc/bashrc
# /etc/csh.cshrc
# /etc/profile
# /etc/zprofile
# /etc/zshrc
2>/dev/null files /etc/ | natsort | replace '//' '/' | narrow '(rc|profile)' '(bash|zsh|csh|profile)' '!Apple_Terminal'

# dotfiles under home dir.
2>/dev/null files ~ | narrow "$USER/[.]" '!_sessions' '![.]git/' '![.]vim/bundle' '![.]DS_Store' '![.]CFUser' '![.]json$' '![.]bak$' '!_history$'
