#!/bin/sh

# Maybe someday fall back to something else.
#exec mvim "$@"

# Turns out the above wasn't suitable for writing commit messages.
# https://superuser.com/questions/628390/making-macvim-gvim-block-the-terminal-until-closed
exec mvim -f "$@"
