#!/usr/bin/env python3

#==============================================================================
# Functionality
#==============================================================================
import pdb
import sys
import os
import re

# utility funcs, classes, etc go here.

def asserting(cond):
    if not cond:
        pdb.set_trace()
    assert(cond)

def has_stdin():
    return not sys.stdin.isatty()

def reg(pat, flags=0):
    return re.compile(pat, re.VERBOSE | flags)

#==============================================================================
# Cmdline
#==============================================================================
import argparse

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, 
    description="""
TODO
""")
     
parser.add_argument('-v', '--verbose',
    action="store_true",
    help="verbose output" )
     
parser.add_argument('-e', '--exponent',
    default=2.0,
    type=float,
    help="the exponential backoff exponent to use. (default: double the first number.)" )

args = None

#==============================================================================
# Main
#==============================================================================

def tonumber(x):
  if not isinstance(x, str):
    return x
  if '.' in x:
    return float(x)
  else:
    return int(x)

def exponentially(nums, exponent=2):
  if len(nums) > 0:
    first = nums[0]
    yield first
    til = first * exponent
    for num in nums:
      if num >= til:
        yield num
        til = num * exponent

def run():
    if args.verbose:
        print(args)
    if len(args.args) <= 0 and not has_stdin():
        # if there were no args and there was no input, prompt user.
        print('Enter input (press Ctrl-D when done):')
    if len(args.args) <= 0 or has_stdin():
        indata = sys.stdin.read()
        args.args.extend(indata.splitlines())
    numbers = [tonumber(x) for x in args.args]
    # for each arg on cmdline...
    for num in exponentially(numbers, exponent=args.exponent):
        print(num)

def main():
    try:
        global args
        if not args:
            args, leftovers = parser.parse_known_args()
            args.args = leftovers
        return run()
    except IOError:
        # http://stackoverflow.com/questions/15793886/how-to-avoid-a-broken-pipe-error-when-printing-a-large-amount-of-formatted-data
        try:
            sys.stdout.close()
        except IOError:
            pass
        try:
            sys.stderr.close()
        except IOError:
            pass

if __name__ == "__main__":
    main()

