#!/usr/bin/env python

import sys
import scrap
import pipes

sys.path.append("%s/bin" % scrap.getenv('HOME'))

cmd = ' '.join([x for x in sys.argv[1:]])
#cmd = pipes.quote(cmd)
#print cmd
#sys.exit()

for line in sys.stdin:
    scrap.cmd(cmd, stdin=line, shell=True)

