#!/bin/bash

repo="$1"
shift 1
dstdir="$1"
shift 1
upstream="$1"
shift 1
branch="$1"
shift 1

if [ -z "$repo" ]; then
  1>&2 echo "  ghclone foo/bar"
  1>&2 echo "is shorthand for"
  1>&2 echo "  git clone https://github.com/foo/bar"
  1>&2 echo ""
  1>&2 echo "to clone to a different directory:"
  1>&2 echo "  ghclone foo/bar dstdir"
  1>&2 echo ""
  1>&2 echo "to also add an 'upstream' remote whose url is 'https://github.com/original/bar':"
  1>&2 echo "  ghclone foo/bar dstdir original/bar"
  1>&2 echo ""
  1>&2 echo "to do all of the above and then 'git pull upstream master':"
  1>&2 echo "  ghclone foo/bar dstdir original/bar master"
  1>&2 echo ""
  exit 1
fi

if [ -z "${dstdir}" ]; then
  exec git clone "https://github.com/${repo}"
fi

if [ -e "${dstdir}" ]; then
  1>&2 echo "already exists: ${dstdir}"
  exit 1
fi

git clone "https://github.com/${repo}" "${dstdir}"
cd "${dstdir}"

if [ ! -z "${upstream}" ]; then
  git remote add upstream "https://github.com/${upstream}"

  if [ ! -z "${branch}" ]; then
    git pull upstream "${branch}"
  fi
fi
  


