#!/bin/sh
echo "------------------------------------------------------"
echo "git clean -f -d -n -e .*"
echo "------------------------------------------------------"

echo "Warning: about to delete untracked files/folders and uncommitted changes."
read -r -p "Continue? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  :
else
  exit 1
fi

git reset HEAD
git checkout -- .
git clean -f -d -e ".*" "$@"
git status


