#!/bin/bash

read -r -p "Delete local branch '$*'? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  git branch -D $*
fi

read -r -p "Delete *REMOTE* branch '$*'? [y/N] " response
if [[ $response =~ ^([yY][eE][sS]|[yY])$ ]]; then
  git push origin --delete $*
fi

