#!/bin/bash
# https://stackoverflow.com/questions/2706797/finding-what-branch-a-git-commit-came-from

commit="${1}"
shift 1

if [ -z "${commit}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <commit> [<option>]"
    exit 1
fi

set -x

exec git branch -a --contains "${commit}" "$@"
