#!/bin/bash
# http://stackoverflow.com/questions/855767/can-i-use-git-diff-on-untracked-files

git diff "$@"
git ls-files --others --exclude-standard | while read -r i; do git diff "$@" -- /dev/null "$i"; done

