#!/bin/bash

branch_name=$1
if [ -z "$branch_name" ]; then
  echo "github-branch-create <branch_name>"
  exit 1
fi

#git checkout -b $branch_name && git push origin $branch_name
git checkout -b $branch_name && git push --set-upstream origin $branch_name

