#!/bin/bash

from="$1"
shift 1

if [ -z "$from" ]; then
  1>&2 echo "  ghclone foo/bar"
  1>&2 echo "is shorthand for"
  1>&2 echo "  git clone https://github.com/foo/bar"
  1>&2 echo ""
  1>&2 echo "this works too:"
  1>&2 echo "  ghclone foo/bar dstdir"
  1>&2 echo ""
  exit 1
fi

# cat <<EOF
# exec git clone "https://github.com/${from}" "$@"
# EOF
exec git clone "https://github.com/${from}" "$@"

