#!/bin/sh

set -e

for model_dir in "$@"
do
  model_dir="$(file-name-as-directory "$model_dir")"
  unbuffer gsutil ls "${model_dir}**/checkpoint" | rg -o '(.*?)/checkpoint([^/])' --replace '$1/$2' --color=never
done
