#!/usr/bin/env python
import sys
import argparse
import hashlib

parser = argparse.ArgumentParser()
parser.add_argument('hashname')
parser.add_argument('infile', nargs='?', type=argparse.FileType('r'),
                    default=sys.stdin)
args = parser.parse_args()

m = hashlib.new(args.hashname)
m.update(args.infile.read())
print m.hexdigest()

