#!/usr/bin/env python3
import sys
import argparse
import hashlib

parser = argparse.ArgumentParser()
parser.add_argument('hashname')
parser.add_argument('infile', nargs='?', type=argparse.FileType('r'),
                    default=sys.stdin)
args = parser.parse_args()

m = hashlib.new(args.hashname)
m.update(args.infile.buffer.read())
print(m.hexdigest())

