#!/usr/bin/env python

import fileinput
import sys
import humanbytes
import re

args = sys.argv[1:]
if len(args) <= 0:
    pass

suffix = r'[bBkKmMgGtTpP]'

getcol1 = re.compile(r'^ (?P<prefix> [\s\[]* ) (?P<match> [\d.]+[\s]?' + suffix + r'? ) \s (?P<rest> .*)', re.VERBOSE)

for line in fileinput.input():
    orig = line
    line = line.strip()
    m = getcol1.search(line)
    if m:
        prefix = m.expand(r'\g<prefix>')
        inp = m.expand(r'\g<match>')
        # add suffix if it doesn't exist.
        if not re.compile(suffix, re.VERBOSE).search(inp):
            inp = inp + 'B'
        rest = m.expand(r'\g<rest>')
        outp = humanbytes.human2bytes(inp)
        prefix = '' # HACK: disabling this for `tree`
        sys.stdout.write("%s %s %s\n" % (prefix, outp, rest))
    else:
        sys.stdout.write(orig)

