#!/usr/bin/env python
import sys

if __name__ == "__main__":
    cmd = ' '.join(sys.argv[1:])
    sys.stdout.write(cmd)
    sys.stdout.write('\n')
    while True:
        b = sys.stdin.read(1)
        sys.stdout.write(b)


