#!/bin/sh

# cat <<'EOF'
# find . -type f -printf '%T@ %p\n' | sort -k 1 -n | sed 's/^[^ ]* //'
# EOF
# find . -type f -printf '%T@ %p\n' | sort -k 1 -n | sed 's/^[^ ]* //'

cols 1:3 0 ,3: | natsort "$@" | cols ,1 ,0 ,2:


