#!/bin/bash

echoerr() { echo "$@" 1>&2; }

opts=
opts2="$@"

# examine cwd if nothing was specified.
# if [ -z "$opts2" ]; then
#   opts2="."
# fi

# if colorization wasn't disabled, then add it.
if [ -z "$(printf "%s" "$opts2" | flags \\-n)" ]; then
  opts="$opts -C"
fi

# cat <<EOF
# tree $opts $opts2
# EOF

# don't use -F, breaks grep

# cat <<EOF
# tree -l -D -h -i -f --ignore-case --noreport --dirsfirst --timefmt "%Y-%m-%d %T" $opts "$@"
# EOF

read -r -d '' output <<EOF
`tree -l -D -h -i -f --ignore-case --noreport --dirsfirst --timefmt "%Y-%m-%d %T" $opts "$@"`
EOF

# WARNING: HAX.
printf "%s" "$output" | contains '.* error [\s] opening [\s] dir .*'
status=$?
if [ $status -gt 0 ]; then
  #echo "status $status"
  #echo "output $output"
  1>&2 printf "%s\n" "$(echo "$output" | igrep 'error opening')"
  exit $status
else
# END HAX.

  # the resub is to get rid of the pesky [ ] from tree's output, to make
  # sorting easier

  # the second resub is to remove lines which don't contain numbers,
  # since tree insists on printing each directory name.
  # Actually, forget the second resub.  Just never give lltree more
  # than one path.


  printf "%s\n" "$output" | skip-n-lines 1 | resub '\[ (.*?) \] (.*)' '\1\2' \
    #| cols 0 ,1:3 ,3: | resub '[^/]+ NIL [^/]+' ''
fi

