#!/usr/bin/env python
import fileinput
import sys

args = [x.decode('unicode-escape') for x in sys.argv[1:]]
if len(args) <= 0:
    args = [' ', '\n', '\r', '\t']

def ltrim(x, of):
    for o in of:
        if x.startswith(o):
            return ltrim(x[len(o):], of)
    return x

data = sys.stdin.read()
data = ltrim(data, args)
sys.stdout.write(data)

