#!/usr/bin/env python
import fileinput
import sys
import os

args = sys.argv[1:]
if len(args) <= 0:
    pass

# Each argument is a filename.

# Echo each filename and then the contents of the file.

for filename in args:
    if not os.path.isfile(filename):
        sys.stderr.write('not a file: %s\n' % filename)
        continue

    with open(filename) as f:
        sys.stdout.write('%s\n' % filename)
        sys.stdout.write('%s\n' % f.read())

