#!/bin/sh
#exec wget --tries=5 --mirror --no-check-certificate --convert-links "$@"

# https://stackoverflow.com/questions/18225548/mirroring-a-website-and-maintaining-url-structure
set -x
exec wget -r -l inf -k -nc -nH -p -E -e robots=off "$@"
