#!/bin/sh

set -ex

index="${1}"
shift 1
cores="${1}"
shift 1

set +x

cidr="10.$(math $index + 2).0.0/$(python3 -c "import math; import sys; print(int(32 + 2 - math.log2(int(sys.argv[1]))))" ${cores})"

cat <<EOF
gcloud compute tpus create tpu-v3-${cores}-euw4a-${index} --zone europe-west4-a --project gpt-2-15b-poetry --network tpu-euw4a --range ${cidr} --version 1.15 --accelerator-type v3-${cores} --preemptible
EOF
