#!/usr/bin/env python

#==============================================================================
# Functionality
#==============================================================================

# utility funcs, classes, etc go here.

#==============================================================================
# Cmdline
#==============================================================================
import argparse

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, 
    description="""
TODO
""")
     
parser.add_argument('-r', '--reverse',
    action="store_true",
    help="reverse sort order" )

#==============================================================================
# Main
#==============================================================================
import sys
import pdb
import natsort

def main():
    lines = [line for line in sys.stdin]
    for line in natsort.natsorted(lines, reverse=args.reverse):
        sys.stdout.write(line)

if __name__ == "__main__":
    args = parser.parse_args()
    main()


