#!/bin/sh

1>&2 echo "paulgraham.com/ind.html"
curl -fsSL "paulgraham.com/ind.html" | pg-index-process | grep -v 'href="ind[_.]';

for i in {1..999}
do
  sleep 0.1
  1>&2 echo "paulgraham.com/ind_${i}.html"
  data="$(curl -fsSL "paulgraham.com/ind_${i}.html")"
  links="$(printf "%s" "$data" | pg-index-process)"
  output="$(printf "%s" "$links" | grep -v 'href="ind[_.]')"
  if [ -z "$output" ]
  then
    if [ -z "$(printf "%s" "$links" | grep '>Next</a>')" ]
    then
      break
    fi
  fi
  printf "%s\n" "$output"
done
