#!/usr/bin/env python3
import sys

def has_stdin():
    return not sys.stdin.isatty()

if has_stdin():
    for line in sys.stdin:
        sys.stdout.write(line.rstrip() + '\x00')
else:
    for x in sys.argv[1:]:
        sys.stdout.write(x + '\x00')


