#!/bin/sh

dir="${1}"
shift 1

if [ -z "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <directory> [<option>]"
    exit 1
fi

set -e

curl -fsSL "https://pypi.org/pypi/${dir}/json" | exec yq "$@"
