#!/bin/sh

lib="${1}"
shift 1

if [ -z "${lib}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <libname> [<option>]"
    exit 1
fi

set -e

curl -fsSL "https://pypi.org/pypi/${lib}/json" | exec jq "$@"
