#!/usr/bin/env python

#==============================================================================
# Functionality
#==============================================================================

# utility funcs, classes, etc go here.

#==============================================================================
# Cmdline
#==============================================================================
import argparse

parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter, 
    description="""
Prints a random integer in the range [min, max] inclusive.
""")

parser.add_argument('min', nargs='?')
parser.add_argument('max')
        

#==============================================================================
# Main
#==============================================================================
import sys
from random import randint

def main():
    #print args
    lo = int(args.min) if args.min else 0
    hi = int(args.max)
    print randint(lo, hi)

if __name__ == "__main__":
    args = parser.parse_args()
    main()

