#!/usr/bin/env python
import re
import sys

args = sys.argv[1:]
if len(args) > 0:
    sys.stdout.write(' '.join([re.escape(arg) for arg in args]))
else:
    sys.stdout.write(re.escape(sys.stdin.read().rstrip('\n\r')))

