#!/bin/bash

dir="${1}"
shift 1

if [ ! -d "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <directory>"
    exit 1
fi

set -x
exec restic -r ~/restic backup "${dir}" --insecure-no-password
