#!/usr/bin/env python3
import sys

def main():
  for line in [line for line in sys.stdin][::-1]:
      sys.stdout.write(line)
      sys.stdout.flush()

if __name__ == '__main__':
  import scrap_utils
  scrap_utils.pipeline(main)
