#!/bin/sh
exec rg-pager --line-number --column -g '!*.min.*' -g '!*.map' -g '!*angular*.js' -g '!*angular-1.6*' -g '!*/docs/*'  -g '!zepto/index.js' -g '!Octane_Closure/code-load.js_c' -g '!SunSpider/string-unpack-code.js' -g '!*/bundle.js' -g '!*.min.*' "$@"
