#!/usr/bin/env python3
import fileinput
import sys

args = [x.encode('utf8').decode('unicode-escape') for x in sys.argv[1:]]
if len(args) <= 0:
    args = [' ', '\n', '\r', '\t']

def rtrim(x, of):
    for o in of:
        if x.endswith(o):
            return rtrim(x[:-len(o)], of)
    return x

data = sys.stdin.read()
data = rtrim(data, args)
sys.stdout.write(data)
