#!/bin/bash

HASH=sha1

#while [ $# -ne 0 ]; do
#  echo hi
#  echo "$1"
#  FILE="$1"
#  shift 1;
#  printf "%s\t" "$FILE"
#  printf "%s\n" $(cat "$FILE" | hashing $HASH)
#done

if [ -z "$1" ]; then
  echo 'sha1sum <file>'
  exit 1
fi

while [ ! -z "$1" ]; do
  FILE="$1"
  shift 1
  printf "%s\t" "$FILE"
  printf "%s\n" $(cat "$FILE" | hashing $HASH)
done


