#!/bin/bash
set -e

# https://unix.stackexchange.com/questions/445469/shell-quote-string-with-single-quotes-rather-than-backslashes
quote () { printf %s\\n "$1" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/" ; }

if [ $# = 0 ]
then
  quote "$(cat)"
else
  while [ ! -z "$*" ]
  do
    quote "${1}"
    shift
  done
fi

