#!/bin/sh

if [ ! -z "${VERBOSE}" ]
then
  set -x
fi

osa() {
  osascript -e "${1}" 2>&1
}

script='
tell application "VLC"
    -- log (get name of current item)
    log (get path of current item)
end tell'

path="$(osa "${script}" | replace "`pwd`/" "" | trim)"

if [ -z "${path}" ]
then
  exit 1
fi

echo $path
exec spectrogram-of "${path}"

