#!/bin/bash

dir="${1}"
stamp="${2:-$(utcstamp)}"
shift 2

if [ ! -d "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <directory>"
    exit 1
fi

set -x
exec tarsnap -v -c -f "${dir}-${stamp}" "${dir}"

