#!/bin/sh

dir="${1}"
shift 1

if [ -z "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <directory> [<option>]"
    exit 1
fi

port="${1:-0}"
shift 1

host="${HOST:-0.0.0.0}"

set -x
exec tensorboard --host "${host}" --port "${port}" --logdir "$dir" "$@"

