#!/bin/bash

dir="${1}"
shift 1

if [ -z "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <working directory> [<option>]"
    exit 1
fi

set -ex

export LD_LIBRARY_PATH=/tfk/lib;
exec jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' --port=8888 --NotebookApp.port_retries=0 --notebook-dir="${dir}" "$@"

