#!/bin/sh

dir="${1}"
shift 1

if [ -z "${dir}" ]
then
    1>&2 echo "usage:"
    1>&2 echo "  ${0} <directory> [<option>]"
    exit 1
fi

set -ex
cat "$dir" | tfevents-parse | tfevents-parse-events -c  | tfevents-upload-images | tee "${dir}.json.tmp"
mv "${dir}.json.tmp" "${dir}.json"

