#!/usr/bin/env python3

import sys
import fileinput
import os
import subprocess

if __name__ == "__main__":
    p = subprocess.Popen(["xxd", "-p"], stdout=subprocess.PIPE, stdin=sys.stdin)
    out, err = p.communicate()
    sys.stdout.buffer.write(out.replace(b'\n',b'').replace(b'\r',b'').strip())

