#!/bin/sh

i="${1}"
shift 1

if [ -z "${i}" ]
then
    echo "usage:"
    echo "  ${0} <i> [<option>]"
    exit 1
fi

set -x
exec gcloud compute tpus create tpuncle${i} --zone us-central1-a --network default --range 10.47.${i}.0/29 --version 1.15 --accelerator-type "v3-8" --preemptible "$@"
