#!/bin/sh

i="${1}"
shift 1

if [ -z "${i}" ]
then
    echo "usage:"
    echo "  ${0} <i> [<option>]"
    exit 1
fi

set -x
exec gcloud compute tpus create tpo-euw4a-${i} --zone europe-west4-a --network tpu-euw4a --range 10.49.${i}.0/29 --version 1.15 --accelerator-type "v3-8" "$@"
