#!/bin/sh
set -x
for i in 0 {4..9} {20..28}; do tpu-delete-quiet tpu-v3-32-euw4a-$i ; done
tpu-delete-quiet tpu-v3-512-euw4a-10
tpu-delete-quiet tpu-v3-512-euw4a-11
tpu-delete-quiet tpu-v3-512-euw4a-12
tpu-delete-quiet tpu-v3-256-euw4a-13
tpu-delete-quiet tpu-v3-128-euw4a-14
sleep ${1:-300}
for i in 0 {4..9} {20..28}; do tpu-create-eu-pod-v3-32 $i --async; done
tpu-create-eu-pod 10 v3-512 25 --async
tpu-create-eu-pod 11 v3-512 25 --async
tpu-create-eu-pod 12 v3-512 25 --async
tpu-create-eu-pod 13 v3-256 26 --async
tpu-create-eu-pod 14 v3-128 27 --async
