#!/usr/bin/env python3

# Make sure the Colab Runtime is set to Accelerator: TPU.
import requests
import os
import sys
version=sys.argv[1]
tpus=sys.argv[2:]
for tpu in tpus:
  url = 'http://' + tpu.split(':')[0] + ':8475/requestversion/{version}'.format(version=version)
  print('curl -X POST ' + url)
