#!/bin/bash
gcloud compute tpus list --zone europe-west4-a "$@" | natsort | replace '        ' ' ' | replace '          ' ''
gcloud compute tpus list --zone us-central1-a "$@" | skip-first-n-lines 1 | natsort | replace '        ' ' ' | replace '          ' ''
