#!/bin/sh

dir="${1}"
shift 1

if [ -z "${dir}" ]
then
    echo "usage:"
    echo "  ${0} <directory> [<option>]"
    exit 1
fi

set -x
exec gcloud compute tpus delete --zone europe-west4-a tpewdiepie$dir "$@"
