#!/usr/bin/env python3

import urllib
import sys
import fileinput

def main():
  out = ''.join(line for line in fileinput.input())
  sys.stdout.write(out.strip())


if __name__ == '__main__':
  import scrap_utils
  scrap_utils.pipeline(main)
