#!/usr/bin/env python

import sys
import re
import pdb
from scrap import hexstr

data = sys.stdin.read()

def filtering(data):
    for i in xrange(256):
        c = chr(i)

        # we need to escape backslashes.
        if c == '\\': 
            c += c

        replace = r'\x' + hexstr(i)
        pattern = re.compile(re.escape(replace), re.IGNORECASE)
        data = pattern.sub(c, data)
    return data

data = filtering(data)

sys.stdout.write(data)


